/*
 * proton.js
 * An implementation of the proton protocol in pure javascript
 * Nicholas Boucher & Aron Szanto
 * April 2018
 */

/*
 * Encodes the passed `obj` with the proton protocol and returns the
 * generated bytestring
 */
 function protonEncode(obj) {
   return ""
 }

/* Decodes the passed `bytestr` using the proton protocol and returns the
 * stored object
 */
 function protonDecode(bytestr) {
   return {}
 }
