# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: string_int.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='string_int.proto',
  package='autoprotobuf',
  syntax='proto3',
  serialized_pb=_b('\n\x10string_int.proto\x12\x0c\x61utoprotobuf\"(\n\x0cKeyStringInt\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0b\n\x03val\x18\x02 \x01(\x05\x62\x06proto3')
)




_KEYSTRINGINT = _descriptor.Descriptor(
  name='KeyStringInt',
  full_name='autoprotobuf.KeyStringInt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='autoprotobuf.KeyStringInt.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='val', full_name='autoprotobuf.KeyStringInt.val', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['KeyStringInt'] = _KEYSTRINGINT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KeyStringInt = _reflection.GeneratedProtocolMessageType('KeyStringInt', (_message.Message,), dict(
  DESCRIPTOR = _KEYSTRINGINT,
  __module__ = 'string_int_pb2'
  # @@protoc_insertion_point(class_scope:autoprotobuf.KeyStringInt)
  ))
_sym_db.RegisterMessage(KeyStringInt)


# @@protoc_insertion_point(module_scope)
